### PR TITLE
fixes, 3rd edition

### PR DESCRIPTION
**Pull request by phi-gamma**
Fontloader updated to the latest beta; this includes improvements
especially regarding Type1 loading.

Luaotfload issues addressed: #356 (possibly #363), #359 (possibly
#325), #358, #357, #349, #344, and, as usual,  a number of other
untracked issues that surfaced during testing.

### CODE REVIEW

**Comment by dohyunkim** [comment]
After the update, an error occurs when I issue `luaotfload-tool -u`.
```
.../luaotfload-database.lua:3199: attempt to index field 'meta' (a nil value)
``` 
It seems to be that `currentnames` at line 3196 is now empty table, not nil anymore, so that `load_names` function has not been executed.

**Comment by phi-gamma** [comment]
Hi,

thanks for the report.

···<date: 2016-06-14, Tuesday>···<from: Dohyun Kim>···

> After the update, an error occurs when I issue `luaotfload-tool -u`.
> ```
> .../luaotfload-database.lua:3199: attempt to index field 'meta' (a nil value)
> ``` 
> It seems to be that `currentnames` at line 3196 is now empty
> table, not nil anymore, so that `load_names` function has not
> been executed.

What version is the database (meta.version)?

Best,
Philipp

**Comment by phi-gamma** [comment]
···<date: 2016-06-15, Wednesday>···<from: phg>···

> Hi,
> 
> thanks for the report.
> 
> ···<date: 2016-06-14, Tuesday>···<from: Dohyun Kim>···
> 
> > After the update, an error occurs when I issue `luaotfload-tool -u`.
> > ```
> > .../luaotfload-database.lua:3199: attempt to index field 'meta' (a nil value)
> > ``` 
> > It seems to be that `currentnames` at line 3196 is now empty
> > table, not nil anymore, so that `load_names` function has not
> > been executed.
> 
> What version is the database (meta.version)?

Scratch that; please check the latest PR.

**Comment by dohyunkim** [comment]
2016-06-15 14:53 GMT+09:00 Philipp Gesang <notifications@github.com>:

> ···<date: 2016-06-15, Wednesday>···<from: phg>···
>
> > Hi,
> >
> > thanks for the report.
> >
> > ···<date: 2016-06-14, Tuesday>···<from: Dohyun Kim>···
> >
> > > After the update, an error occurs when I issue `luaotfload-tool -u`.
> > > ```
> > > .../luaotfload-database.lua:3199: attempt to index field 'meta' (a nil
> value)
> > > ```
> > > It seems to be that `currentnames` at line 3196 is now empty
> > > table, not nil anymore, so that `load_names` function has not
> > > been executed.
> >
> > What version is the database (meta.version)?
>
> Scratch that; please check the latest PR.
>
>
Works ok now. Thanks for the quick fix.

**Pull request merged**
